os:
  - osx
language: node_js
node_js:
  - "0.10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sassc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --devel sass/sass/sass ; fi
