os:
  - osx
osx_image: xcode9.3
language: node_js
node_js:
  - "0.10"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sassc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install --devel sass/sass/sass ; fi
